config/routes.rb
MoltoSoldi::Application.routes.draw do
  
  match "transactions/:action", :controller => 'transactions', :action => /[a-z]+/i
  resources :authentications
  resources :transactions
  resources :friends
  resources :posts
  resources :mails
  
  match '/auth/:provider/callback' => 'authentications#create'

  devise_for :users, path_names: {sign_in: "login", sign_out: "logout"},
                       controllers: {omniauth_callbacks: "authentications", registrations: "registrations"}

  root to: 'static_pages#home'
  match '/users/:id', to: 'users#show'
  match '/allusers', to: 'users#index'
  match '/help',    to: 'static_pages#help'
  match '/about',   to: 'static_pages#about'
  match '/contact', to: 'static_pages#contact'
  
  resources :users do
    member do
      get :borrows, :lends
    end
  end

  get "static_pages/home"
  get "static_pages/about"
  get "static_pages/help"

end

app/models/friend.rb
class Friend < ActiveRecord::Base
  attr_accessible :email, :name, :user_id
  
  belongs_to :user
  
  before_save {|user| user.email = email.downcase}
  
  validates :name, presence: true, length: { maximum: 50 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence:   true,
                    format:     { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }
end

app/controllers/friends_controller.rb
class FriendsController < ApplicationController
  
   before_filter :authenticate_user!
  # GET /friends
  # GET /friends.json
  def index
    @friends = current_user.friends.paginate(page: params[:page], per_page: 10)
    
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @friends }
    end
  end

  # GET /friends/1
  # GET /friends/1.json
  def show
    @friend = Friend.find(params[:id])
    @transactions = current_user.transactions.where(:friend_id => @friend.id).paginate(page: params[:page], per_page: 5)

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @friend }
    end
  end

  # GET /friends/new
  # GET /friends/new.json
  def new
    @friend = Friend.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @friend }
    end
  end

  # GET /friends/1/edit
  def edit
    @friend = Friend.find(params[:id])
  end

  # POST /friends
  # POST /friends.json
  def create
    @friend = current_user.friends.build(params[:friend])

    respond_to do |format|
      if @friend.save
        format.html { redirect_to @friend, notice: 'Friend was successfully created.' }
        format.json { render json: @friend, status: :created, location: @friend }
      else
        format.html { render action: "new" }
        format.json { render json: @friend.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /friends/1
  # PUT /friends/1.json
  def update
    @friend = Friend.find(params[:id])

    respond_to do |format|
      if @friend.update_attributes(params[:friend])
        format.html { redirect_to @friend, notice: 'Friend was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @friend.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /friends/1
  # DELETE /friends/1.json
  def destroy
    @friend = Friend.find(params[:id])
    @friend.destroy

    respond_to do |format|
      format.html { redirect_to friends_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/friends_helper.rb
module FriendsHelper
end

app/views/friends/_form.html.erb
<%= form_for(@friend) do |f| %>
  <% if @friend.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@friend.errors.count, "error") %> prohibited this friend from being saved:</h2>

      <ul>
      <% @friend.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/friends/_friend.html.erb
<li>
  <%= gravatar_for friend, size: 52 %>
  <%= link_to friend.name, '/friends/' + friend.id.to_s %>
  <br><%= friend.email%><br><td><%= link_to 'Edit', edit_friend_path(friend) %></td>
  <td><%= link_to 'Destroy', friend, method: :delete, data: { confirm: 'Are you sure?' } %></td>
</li>

app/views/friends/edit.html.erb
<h1>Editing friend</h1>

<%= render 'form' %>

<%= link_to 'Show', @friend %> |
<%= link_to 'Back', friends_path %>

app/views/friends/index.html.erb
<% provide(:title, 'Listing Friends') %>
<h1>All friends</h1>

<%= will_paginate %>

<ul class="users">
  <%= render @friends %>
</ul>

<%= will_paginate %>

<br>
<%= link_to 'New Friend', new_friend_path %>

app/views/friends/new.html.erb
<h1>New friend</h1>

<%= render 'form' %>

<%= link_to 'Back', friends_path %>

app/views/friends/show.html.erb
<% provide(:title, @friend.name) %>

<p id="notice"><%= notice %></p>

<div class="row">
  <aside class="span4">
    <p>
	 <%= gravatar_for @friend %>
	<p>
	<br><br>
	  <b>Name:</b>
	  <%= @friend.name %>
	  <br><b>Email:</b>
	  <%= @friend.email %>
	</p>
	<%= render 'shared/landborrowbuttons' %>

  </aside>

	<div class="span8">
		<%= render 'shared/transactionsindex' %>
	</div>
</div>


<%= link_to 'Edit', edit_friend_path(@friend) %> |
<%= link_to 'Back', friends_path %>