config/routes.rb
MoltoSoldi::Application.routes.draw do
  
  match "transactions/:action", :controller => 'transactions', :action => /[a-z]+/i
  resources :authentications
  resources :transactions
  resources :friends
  resources :posts
  resources :mails
  
  match '/auth/:provider/callback' => 'authentications#create'

  devise_for :users, path_names: {sign_in: "login", sign_out: "logout"},
                       controllers: {omniauth_callbacks: "authentications", registrations: "registrations"}

  root to: 'static_pages#home'
  match '/users/:id', to: 'users#show'
  match '/allusers', to: 'users#index'
  match '/help',    to: 'static_pages#help'
  match '/about',   to: 'static_pages#about'
  match '/contact', to: 'static_pages#contact'
  
  resources :users do
    member do
      get :borrows, :lends
    end
  end

  get "static_pages/home"
  get "static_pages/about"
  get "static_pages/help"

end

app/views/shared/_calendarview.html.erb
<h2>Calendar View</h2>
	<div id="transactions">
	
	  <h2 id="month">
	    <%= link_to "<", date: @date.prev_month %>
	    <%= @date.strftime("%B %Y") %>
	    <%= link_to ">", date: @date.next_month %>
	  </h2>
	  <%= calendar @date do |date| %>
	    <%= date.day %>
	    <% if @transactions_by_date[date] %>
	      <ul>
	        <% @transactions_by_date[date].each do |transaction| %>
	          <li><%= link_to Friend.find(transaction.friend_id).name + " - " + transaction.amount.to_s, edit_transaction_path(transaction) %></li>
	        <% end %>
	      </ul>
	    <% end %>
	  <% end %>
	</div>

app/views/shared/_landborrowbuttons.html.erb
<%= link_to "Borrow Money", new_transaction_url(:friend_id => @friend.id, :t_type => 1, :status => 0), 
                        class: "btn btn-small btn-primary" %>
<% if current_user.transactions.where(:friend_id => @friend.id, :t_type => 2).exists? %>
<%= link_to "Lend Money", new_transaction_url(:friend_id => @friend.id, :t_type => 2, :status => 0), 
                          class: "btn btn-small btn-secondary", data: { confirm: 'Your friend still has dept. Do you still want to continue ?' } %>
<% else %>
<%= link_to "Lend Money", new_transaction_url(:friend_id => @friend.id, :t_type => 2, :status => 0),
                          class: "btn btn-small btn-primary" %>
<% end %>

app/views/shared/_stats.html.erb
<% @user ||= current_user %>
<div class="stats">
  <a href="<%= borrows_user_path(@user) %>">
    <strong id="following" class="stat">
      <%= "€ " + current_user.total_borrows.to_s %>
    </strong>
    borrows
  </a>
  <a href="<%= lends_user_path(@user) %>">
    <strong id="followers" class="stat">
      <%= "€ " + current_user.total_lends.to_s %>
    </strong>
    lends
  </a>
</div>

app/views/shared/_transactionfeed.html.erb
<h3>Active Transactions (<%= @user.transactions.where(:status => 0).count %>)</h3><br>
<% if @user.transactions.any? %>
  
  <ol class="transactions">
    <%= render @transactions %>
  </ol>
  <%= will_paginate @transactions %>
<% else %>
You don't have any transactions. <br>Why don't you add from <%= link_to "here ?", transactions_url %>
<% end %>

app/views/shared/_transactions.html.erb
		<h2>Listing <%= whichTransaction(params[:status]) %> transactions</h2>	
		<br><%= link_to 'New Transaction', new_transaction_path %><br>
		
<% if @transactions.exists? %>	
<% @transactions.each do |transaction| %>
		
	<div id="posts-list">
		<article class="format-standard">
			<div class="entry-date"><div class="number">€<%= transaction.amount %></div> <div class="year"><%= whatType(transaction.t_type)%></div></div>
			<h2  class="post-heading"><%= link_to Friend.find(transaction.friend_id).name, edit_transaction_path(transaction) %></h2>
			<div class="excerpt">Deadline is in <%= time_diff_in_natural_language(Time.now, transaction.deadline) %>
			</div>
			<% if transaction.status == 0 %>
			<% if transaction.t_type == 2 %>
				<% message = Friend.find(transaction.friend_id).name + " needs to pay " + " € " + transaction.amount.to_s %>
			<% else %>
				<% message = "I need to pay to " + Friend.find(transaction.friend_id).name + " € " + transaction.amount.to_s %>
			<% end %>
			<%= link_to image_tag("icon-twitter.png", alt: "Share on Twitter"), posts_path(:tweet => "#{message} !", :post_type => "twitter"), :method => :post, :remote => true, :class => "button" %>
			<%= link_to image_tag("icon-facebook.png", alt: "Share on FaceBook"), posts_path(:tweet => "#{message} !", :post_type => "facebook"), :method => :post, :remote => true, :class => "button" %>
			<%= link_to image_tag("icon-email.png", alt: "Send Mail"), mails_path(:content => "#{message} ", :email => Friend.find(transaction.friend_id).email, :name => Friend.find(transaction.friend_id).name), :method => :post, :remote => true, :class => "button" %>
			<% end %>
			<div class="meta">
			    <%= link_to 'Destroy', transaction, method: :delete, data: { confirm: 'Are you sure?' }%>
			</div>
		</article>
		
	</div>
		
<% end %>
<% else %>
<br>You don't have any transactions. <br>Why don't you add from <%= link_to "here ?", new_transaction_url %>
<% end %>

<%= will_paginate %>

app/views/shared/_transactionsindex.html.erb
<article class="module width_3_quarter">
<header><h3 class="tabs_involved">Transactions</h3></header>
<table class="tablesorter" cellspacing="0"> 
<thead> 
	<tr> 
		<th>Amount</th>
	    <th>Status</th>
	    <th>Type</th>
	    <th>Time Left</th>
		<th>Actions</th>
	</tr> 
</thead>
<tbody> 
<% @transactions.each do |transaction| %>
	<tr>
	    <td>€ <%= transaction.amount %></td>
	    <td><%= whatType(transaction.t_type) %></td>
		<td><%= whatStat(transaction.status) %></td>
	    <td><%= distance_of_time_in_words(Time.now, transaction.deadline) %></td>
	    <td><%= link_to 'Edit', edit_transaction_path(transaction) %>
		<%= link_to 'Destroy', transaction, method: :delete, data: { confirm: 'Are you sure?' }%>	
			<% if transaction.status == 0 %>
			<% if transaction.t_type == 2 %>
				<% message = Friend.find(transaction.friend_id).name + " needs to pay " + " € " + transaction.amount.to_s %>
			<% else %>
				<% message = "I need to pay to " + Friend.find(transaction.friend_id).name + " € " + transaction.amount.to_s %>
			<% end %>
			 
				<%= link_to image_tag("icon-twitter.png", alt: "Share on Twitter"), posts_path(:tweet => "#{message} !", :post_type => "twitter"), :method => :post, :remote => true, :class => "button" %>
				<%= link_to image_tag("icon-facebook.png", alt: "Share on FaceBook"), posts_path(:tweet => "#{message} !", :post_type => "facebook"), :method => :post, :remote => true, :class => "button" %>
				<%= link_to image_tag("icon-email.png", alt: "Send Mail"), mails_path(:content => "#{message} ", :email => Friend.find(transaction.friend_id).email, :name => Friend.find(transaction.friend_id).name), :method => :post, :remote => true, :class => "button" %></td>
			<% end %>
	   
	</tr>
<% end %>
</table>
<%= will_paginate @transactions %>
</tbody> 
</table>
</article>

app/views/shared/_user_info.erb
 <%= gravatar_for current_user %>

<h1>
  <%= current_user.email %>
</h1>
<span>
  <%= link_to "view my profile", '/users/' + current_user.id.to_s %>
</span>
<span>
  <%= link_to pluralize(current_user.transactions.count, "transaction"), transactions_path %>
</span>

app/views/shared/_user_info.html.erb
 <%= gravatar_for current_user %>

<h1>
  <%= current_user.email %>
</h1>
<span>
  <%= link_to "view my profile", '/users/' + current_user.id.to_s %>
</span>
<span>
  <%= link_to pluralize(current_user.transactions.count, "transaction"), transactions_path %>
</span>