config/routes.rb
MoltoSoldi::Application.routes.draw do
  
  match "transactions/:action", :controller => 'transactions', :action => /[a-z]+/i
  resources :authentications
  resources :transactions
  resources :friends
  resources :posts
  resources :mails
  
  match '/auth/:provider/callback' => 'authentications#create'

  devise_for :users, path_names: {sign_in: "login", sign_out: "logout"},
                       controllers: {omniauth_callbacks: "authentications", registrations: "registrations"}

  root to: 'static_pages#home'
  match '/users/:id', to: 'users#show'
  match '/allusers', to: 'users#index'
  match '/help',    to: 'static_pages#help'
  match '/about',   to: 'static_pages#about'
  match '/contact', to: 'static_pages#contact'
  
  resources :users do
    member do
      get :borrows, :lends
    end
  end

  get "static_pages/home"
  get "static_pages/about"
  get "static_pages/help"

end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
   	<% if user_signed_in? %>
	  Logged in as <strong><%= current_user.email %></strong>.
	  <%= link_to 'Edit profile', edit_user_registration_path %> |
	  <%= link_to "Logout", destroy_user_session_path, method: :delete %>
	<% else %>
	  <%= link_to "Sign up", new_user_registration_path %> |
	  <%= link_to "Login", new_user_session_path %>
	<% end %>
  </small>
  <nav>
    <ul>
      <li><%= link_to "About",   about_path %></li>
      <li><%= link_to "RailsArena", "http://www.railsarena.com" %></li>
      <li><%= link_to "OCC", "http://www.orhancanceylan.com" %></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top">
  <div class="navbar-inner">
    <div class="container">
      <%= link_to "Molto Soldi", root_path, id: "logo" %>
      <nav>
        <ul class="nav pull-right">
          <% if signed_in? %>
 		<li id="fat-menu" class="dropdown">
			<a href="#" class="dropdown-toggle" data-toggle="dropdown">
              Transactions <b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
              <li><%= link_to "Active", transactions_path(:status => 0) %></li>
				<li><%= link_to "Passive", transactions_path(:status => 1) %></li>
            </ul>
 		</li>
            <li><%= link_to "Friends", friends_path %></li>
            <li id="fat-menu" class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                Account <b class="caret"></b>
              </a>
              <ul class="dropdown-menu">
                <li><%= link_to "Profile", '/users/' + current_user.id.to_s %></li>
				<li><%= link_to "Authentications", authentications_url %></li>
                <li><%= link_to "Settings", edit_user_registration_path %></li>
                <li class="divider"></li>
                <li>
                  <%= link_to "Sign out", destroy_user_session_path, method: :delete %>
                </li>
              </ul>
            </li>
          <% else %>
            <li id="fat-menu" class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                Sign In <b class="caret"></b>
              </a>
              <ul class="dropdown-menu">
                <li><%= link_to "Twitter", user_omniauth_authorize_path(:twitter) %></li>
                <li><%= link_to "Facebook", user_omniauth_authorize_path(:facebook) %></li>	
                <li class="divider"></li>
                <li>
                  <li><%= link_to "Sign in", new_user_session_path %></li>
                </li>
              </ul>
            </li>
          <% end %>
        </ul>
      </nav>
    </div>
  </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= stylesheet_link_tag    "application", media: "all" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
    <%= render 'layouts/shim' %>    
  </head>
  <body>
	 <% flash.each do |name, msg| %>
	        <%= content_tag :div, msg, id: "flash_#{name}" %>
	      <% end %>
    <%= render 'layouts/header' %>
    <div class="container">
      <%= yield %>
      <%= render 'layouts/footer' %>
    </div>
  </body>
</html>